In [15]:
import torch
T = torch.tensor([[0.4,0.6],[0.8,0.2]])


In [16]:
T_2 = torch.matrix_power(T,2)

In [17]:
T_2

tensor([[0.6400, 0.3600],
        [0.4800, 0.5200]])

In [18]:
torch.matrix_power(T,5)

tensor([[0.5670, 0.4330],
        [0.5773, 0.4227]])

In [19]:
torch.matrix_power(T,10)

tensor([[0.5715, 0.4285],
        [0.5714, 0.4286]])

In [20]:
v= torch.tensor([[0.7,0.3]])


In [21]:
torch.mm(v, T_2)

tensor([[0.5920, 0.4080]])

In [22]:
T=  torch.tensor([[[0.8,0.1,0.1],[0.1,0.6,0.3]],[[0.7,0.2,0.1],[0.1,0.8,0.1]],[[0.6,0.2,0.2],[0.1,0.4,0.5]]])

In [23]:
T

tensor([[[0.8000, 0.1000, 0.1000],
         [0.1000, 0.6000, 0.3000]],

        [[0.7000, 0.2000, 0.1000],
         [0.1000, 0.8000, 0.1000]],

        [[0.6000, 0.2000, 0.2000],
         [0.1000, 0.4000, 0.5000]]])

In [24]:
R = torch.tensor([1.,0.,-1.])
gamma = 0.5
action =0

In [25]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [26]:

def calc_inv(reward, gamma , trans_matrix):
    inv = torch.inverse(torch.eye(reward.shape[0]) - gamma*trans_matrix)
    return torch.mm(inv , reward.reshape(-1,1))
    # return value

    


In [27]:
trans_matrix = T[:,action]
V = calc_inv(R, gamma, trans_matrix)
print(V)

tensor([[ 1.6787],
        [ 0.6260],
        [-0.4820]])


In [30]:
gamma = 0 
V =  calc_inv(R,gamma, trans_matrix)
V

tensor([[ 1.],
        [ 0.],
        [-1.]])

In [31]:
gamma = 0.99
V = calc_inv(R, gamma, trans_matrix)

In [32]:
V

tensor([[65.8293],
        [64.7194],
        [63.4876]])