In [36]:
import numpy as np 
import gym 
import random 
import time
from IPython.display import clear_output


In [37]:
env = gym.make("FrozenLake-v1")

In [38]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [39]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1

discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001



In [47]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state,_ = env.reset()

    done = False

    rewards_current_episode =0

    for step in range(max_steps_per_episode):

        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])

        else :
            action = env.action_space.sample()

        new_state, reward, done , truncated,info = env.step(action)


    # update q value
       # print(state[0])

        q_table[state,action] = (1-learning_rate)*q_table[state,action]+ learning_rate*(reward + discount_rate*np.max(q_table[new_state,:]))

        state = new_state
        rewards_current_episode += reward

        if done == True:
            break 


    exploration_rate = min_exploration_rate + (max_exploration_rate- min_exploration_rate)*np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)



rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)

count =1000

print("******Average reward per thousand episodes ***************\n")

for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000



print("\n\n *********Q-table************\n")

print(q_table)


******Average reward per thousand episodes ***************

1000 :  0.05000000000000004
2000 :  0.18200000000000013
3000 :  0.3920000000000003
4000 :  0.5700000000000004
5000 :  0.6260000000000004
6000 :  0.6390000000000005
7000 :  0.6740000000000005
8000 :  0.6940000000000005
9000 :  0.6850000000000005
10000 :  0.6780000000000005


 *********Q-table************

[[0.55805662 0.53148224 0.52799566 0.525738  ]
 [0.35913237 0.27616886 0.31883317 0.51922818]
 [0.44049314 0.4131494  0.41125194 0.49902398]
 [0.29318298 0.21909535 0.26198986 0.48252709]
 [0.5828205  0.35504222 0.37729679 0.34830656]
 [0.         0.         0.         0.        ]
 [0.40262179 0.1802377  0.22581883 0.11278046]
 [0.         0.         0.         0.        ]
 [0.25048959 0.45933758 0.3038326  0.62077153]
 [0.40883971 0.68120523 0.40562223 0.45900094]
 [0.71110283 0.4057396  0.29478945 0.33537525]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.30673606 0.52107136

In [46]:
for episode in range(3):
    state,_  = env.reset()
    done = False

    print("***************** Episode", episode +1 , "**************\n\n\n\n")

    time.sleep(1)

    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])
        new_state, reward, done, truncation, info = env.step(action)

        if done : 
            clear_output(wait=True)

            env.render()

            if reward == 1:
                print("****************You reached the goal!************")
                time.sleep(3)

            else:
                print("**************You fell through a hole!************")

                time.sleep(3)

            clear_output(wait=True)

            break
        state = new_state

env.close()

****************You reached the goal!************
