In [1]:
import torch
import torch.nn.functional as F

In [2]:
for i in range(5,-1,-1):
    print (i)

5
4
3
2
1
0


In [3]:
x=[1,2,23,4]
x[::-1]

[4, 23, 2, 1]

In [4]:
x= torch.tensor([1.0,2,3,4])
y = torch.tensor([5,6.7,10,4])

In [5]:
x=torch.stack([x,y])

In [6]:
x[::-1]

ValueError: step must be greater than zero

In [ ]:
x= torch.tensor([0.8,0.2,6,6,7])

In [ ]:
x= [1,54,743,23,6]

In [ ]:
x[::-1]

[6, 23, 743, 54, 1]

In [ ]:

dis = torch.distributions.Normal
mu =torch.tensor([1.0])
sigma =torch.tensor([0.5])

In [ ]:
x= dis(mu,sigma)

In [ ]:
action = x.sample().numpy()


In [ ]:
action

array([-0.81493914], dtype=float32)

In [ ]:
x.log_prob(torch.tensor(action[0]))

tensor([-6.8138])

In [ ]:
x= torch.tensor([30000.0])
F.softplus(x) + 1e-5

tensor([30000.])

In [ ]:
2* sigma

tensor([1.0000, 0.6000, 0.4000])

In [ ]:
test = torch.tensor([1,2,4,5123,42])
test.clip(5,20)

tensor([ 5,  5,  5, 20, 20])

In [ ]:
x= (1,2,3,4,5)
z= tuple(y for y in x)

In [ ]:
z

(1, 2, 3, 4, 5)

In [ ]:
x= torch.randn(3,5,6)
z= tuple(y for y in x)
torch.cat(z)

tensor([[-0.1832, -0.1813, -0.0476,  0.0797,  1.3391,  0.2560],
        [-1.8001,  0.3854,  0.5159, -0.8428,  0.1764, -0.7098],
        [-0.6174,  0.0101, -0.0817,  0.2463, -0.1874,  1.2345],
        [ 0.7534,  0.2573,  0.9307,  0.4757, -0.6788,  0.6412],
        [-0.3301, -0.9960, -0.2734, -0.6728,  1.5178, -0.1348],
        [ 0.1018, -0.9592, -0.1091, -0.5711,  0.0531,  0.0680],
        [ 2.1983,  0.5289, -0.1066,  1.4322, -0.2641, -1.0359],
        [-0.4066, -0.0171,  0.4342, -1.4305, -0.2068,  0.3597],
        [ 0.5096,  0.9581,  0.5659,  0.7622, -1.9731, -0.7328],
        [ 0.2146, -2.0168, -0.3399, -0.6659, -1.1006,  0.9398],
        [ 0.5626,  0.1286,  0.8512,  0.0407, -1.6550, -1.1355],
        [-0.0565,  0.8611,  0.8058, -0.9111,  0.9983,  0.6598],
        [-0.1757,  0.0637,  0.9414,  0.0343,  0.1264, -0.5756],
        [ 1.3571,  1.5116,  1.1532, -0.6112,  0.7894,  1.0937],
        [-0.4694, -1.2225,  0.0197,  0.6557, -1.9093, -0.2654]])

In [ ]:
z

(tensor([[-0.1832, -0.1813, -0.0476,  0.0797,  1.3391,  0.2560],
         [-1.8001,  0.3854,  0.5159, -0.8428,  0.1764, -0.7098],
         [-0.6174,  0.0101, -0.0817,  0.2463, -0.1874,  1.2345],
         [ 0.7534,  0.2573,  0.9307,  0.4757, -0.6788,  0.6412],
         [-0.3301, -0.9960, -0.2734, -0.6728,  1.5178, -0.1348]]),
 tensor([[ 0.1018, -0.9592, -0.1091, -0.5711,  0.0531,  0.0680],
         [ 2.1983,  0.5289, -0.1066,  1.4322, -0.2641, -1.0359],
         [-0.4066, -0.0171,  0.4342, -1.4305, -0.2068,  0.3597],
         [ 0.5096,  0.9581,  0.5659,  0.7622, -1.9731, -0.7328],
         [ 0.2146, -2.0168, -0.3399, -0.6659, -1.1006,  0.9398]]),
 tensor([[ 0.5626,  0.1286,  0.8512,  0.0407, -1.6550, -1.1355],
         [-0.0565,  0.8611,  0.8058, -0.9111,  0.9983,  0.6598],
         [-0.1757,  0.0637,  0.9414,  0.0343,  0.1264, -0.5756],
         [ 1.3571,  1.5116,  1.1532, -0.6112,  0.7894,  1.0937],
         [-0.4694, -1.2225,  0.0197,  0.6557, -1.9093, -0.2654]]))

In [12]:
import numpy as np
a=np.random.random([2,3])


In [13]:
a[:,None] 

array([[[0.75753922, 0.57552857, 0.40793229]],

       [[0.58907009, 0.35515916, 0.84506188]]])