In [8]:
import torch
import torch.nn.functional as F

In [9]:
for i in range(5,-1,-1):
    print (i)

5
4
3
2
1
0


In [10]:
x=[1,2,23,4]
x[::-1]

[4, 23, 2, 1]

In [11]:
x= torch.tensor([1.0,2,3,4])
y = torch.tensor([5,6.7,10,4])

In [12]:
x=torch.stack([x,y])

In [13]:
x[::-1]

ValueError: step must be greater than zero

In [14]:
x= torch.tensor([0.8,0.2,6,6,7])

In [15]:
x= [1,54,743,23,6]

In [16]:
x[::-1]

[6, 23, 743, 54, 1]

In [23]:

dis = torch.distributions.Normal
mu =torch.tensor([1.0])
sigma =torch.tensor([0.5])

In [24]:
x= dis(mu,sigma)

In [25]:
action = x.sample().numpy()


In [35]:
action

array([-0.81493914], dtype=float32)

In [40]:
x.log_prob(torch.tensor(action[0]))

tensor([-6.8138])

In [21]:
x= torch.tensor([30000.0])
F.softplus(x) + 1e-5

tensor([30000.])

In [ ]:
2* sigma

tensor([1.0000, 0.6000, 0.4000])

In [41]:
test = torch.tensor([1,2,4,5123,42])
test.clip(5,20)

tensor([ 5,  5,  5, 20, 20])